#!/usr/bin/env pwsh
# Fleet work rollup (OGDK) - the WORK-state companion to fleet-status (which is git state).
# For every repo under the dev root, tallies OPEN lessons + active plans + the STATUS
# "Next up" line, so the cross-fleet work view scales without hand-maintenance.
# -Write emits FLEET-BOARD.md (a generated board) at the dev root - the data-driven
# dashboard (the hand-curated FLEET-STUDY-SORT.html stays as the showcase).
# Usage: fleet-work.ps1 [-Write] [DevRoot]
# Twin: fleet-work.sh
param([switch]$Write, [string]$DevRoot)
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $DevRoot) { $DevRoot = Split-Path -Parent $RepoRoot }
$Board = Join-Path $DevRoot 'FLEET-BOARD.md'

function OpenCount([string]$f) { if (Test-Path $f) { @(Select-String -LiteralPath $f -Pattern '\*\*Status:\*\* OPEN').Count } else { 0 } }
function PlanCount([string]$d) { $p = Join-Path $d 'docs/plans'; if (Test-Path $p) { @(Get-ChildItem -LiteralPath $p -Filter *.md -File -ErrorAction SilentlyContinue).Count } else { 0 } }
function NextUp([string]$d) {
    $s = Join-Path $d 'docs/STATUS.md'
    if (-not (Test-Path $s)) { return '-' }
    $lines = Get-Content -LiteralPath $s
    $f = $false
    foreach ($ln in $lines) {
        if ($ln -match '^## Next up') { $f = $true; continue }
        if ($f -and $ln -match '^## ') { break }
        if ($f -and $ln -match '^[0-9]+\.') { $t = ($ln -replace '^[0-9]+\.\s*',''); return $t.Substring(0, [Math]::Min(72, $t.Length)) }
    }
    $f = $false
    foreach ($ln in $lines) {
        if ($ln -match '^## Next up') { $f = $true; continue }
        if ($f -and $ln -match '^## ') { break }
        if ($f -and $ln -match '^- ') { $t = ($ln -replace '^-\s*',''); return $t.Substring(0, [Math]::Min(72, $t.Length)) }
    }
    return '-'
}

Write-Host "Fleet work rollup - $DevRoot"
("{0,-16} {1,-7} {2,-7} {3}" -f 'REPO', 'OPEN-L', 'PLANS', 'NEXT UP')
Write-Host ('-' * 80)
$totalOpen = 0
$md = [System.Collections.Generic.List[string]]::new()
$md.Add('# Fleet board'); $md.Add('_Generated by `fleet-work -Write` - do not edit by hand. Companion: FLEET-STUDY-SORT.html._'); $md.Add('')
$md.Add('| Repo | Open lessons | Active plans | Next up |'); $md.Add('|---|---|---|---|')
foreach ($dir in (Get-ChildItem -LiteralPath $DevRoot -Directory)) {
    if (-not (Test-Path (Join-Path $dir.FullName '.git'))) { continue }
    $lf = Join-Path $dir.FullName 'docs/LESSONS.md'; if (-not (Test-Path $lf)) { $lf = Join-Path $dir.FullName 'LESSONS.md' }
    $o = OpenCount $lf; $p = PlanCount $dir.FullName; $n = NextUp $dir.FullName
    $totalOpen += $o
    ("{0,-16} {1,-7} {2,-7} {3}" -f $dir.Name, $o, $p, $n)
    $md.Add("| $($dir.Name) | $o | $p | $($n -replace '\|','\|') |")
}
Write-Host ('-' * 80)
Write-Host "Total OPEN lessons across fleet: $totalOpen"
if ($Write) {
    $md.Add(''); $md.Add("_Total OPEN lessons across fleet: $totalOpen. Generated $(Get-Date -Format yyyy-MM-dd)._")
    Set-Content -LiteralPath $Board -Value $md -Encoding UTF8
    Write-Host "[wrote] $Board"
}
exit 0
# EOF
