#!/usr/bin/env bash
# Fleet work rollup (OGDK) - the WORK-state companion to fleet-status (which is git state).
# For every repo under the dev root, tallies OPEN lessons + active plans + the STATUS
# "Next up" line, so the cross-fleet work view scales without hand-maintenance.
# --write emits FLEET-BOARD.md (a generated board) at the dev root - the data-driven
# dashboard (the hand-curated FLEET-STUDY-SORT.html stays as the showcase).
# Usage: fleet-work.sh [--write] [DEV_ROOT]
# Twin: fleet-work.ps1
set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WRITE=0
if [ "${1:-}" = "--write" ]; then WRITE=1; shift; fi
DEV_ROOT="${1:-$(cd "$REPO_ROOT/.." && pwd)}"
BOARD="$DEV_ROOT/FLEET-BOARD.md"

open_count() {
    # grep -c prints 0 AND exits 1 on no match; a naive `|| echo 0` then emits "0\n0"
    # (the codified grep -c two-zeros lesson) and breaks the $(()) sum. Yield ONE integer.
    [ -f "$1" ] || { echo 0; return; }
    local c
    c="$(grep -c '\*\*Status:\*\* OPEN' "$1" 2>/dev/null || true)"
    echo "${c:-0}"
}

plan_count() {
    local p="$1/docs/plans"
    [ -d "$p" ] || { echo 0; return; }
    find "$p" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' '
}

next_up() {
    local s="$1/docs/STATUS.md"
    [ -f "$s" ] || { echo "-"; return; }
    local n
    n="$(awk '/^## Next up/{f=1;next} f&&/^## /{exit} f&&/^[0-9]+\./{sub(/^[0-9]+\.[[:space:]]*/,"");print;exit}' "$s")"
    [ -z "$n" ] && n="$(awk '/^## Next up/{f=1;next} f&&/^## /{exit} f&&/^- /{sub(/^-[[:space:]]*/,"");print;exit}' "$s")"
    [ -z "$n" ] && n="-"
    printf '%s' "$n" | cut -c1-72
}

echo "Fleet work rollup - $DEV_ROOT"
printf '%-16s %-7s %-7s %s\n' "REPO" "OPEN-L" "PLANS" "NEXT UP"
echo "--------------------------------------------------------------------------------"
total_open=0
md="# Fleet board"$'\n'"_Generated by \`fleet-work --write\` - do not edit by hand. Companion: FLEET-STUDY-SORT.html._"$'\n\n'"| Repo | Open lessons | Active plans | Next up |"$'\n'"|---|---|---|---|"$'\n'
for d in "$DEV_ROOT"/*/; do
    [ -d "${d}.git" ] || continue
    name="$(basename "$d")"
    lf="$d/docs/LESSONS.md"; [ -f "$lf" ] || lf="$d/LESSONS.md"
    o="$(open_count "$lf")"; p="$(plan_count "$d")"; n="$(next_up "$d")"
    total_open=$((total_open + o))
    printf '%-16s %-7s %-7s %s\n' "$name" "$o" "$p" "$n"
    md="$md| $name | $o | $p | $(printf '%s' "$n" | sed 's/|/\\|/g') |"$'\n'
done
echo "--------------------------------------------------------------------------------"
echo "Total OPEN lessons across fleet: $total_open"
if [ "$WRITE" = 1 ]; then
    md="$md"$'\n'"_Total OPEN lessons across fleet: $total_open. Generated $(date +%Y-%m-%d)._"$'\n'
    printf '%s' "$md" > "$BOARD" && echo "[wrote] $BOARD"
fi
exit 0
# EOF
